feat: 페이지 라우팅 작업 및 header, footer 레이아웃 구성
9oormthon-univ/2024_BEOTKKOTTHON_TEAM_28_FE pull request #4
Opened 2024-03-15 15:41 UTC by Sohyunnnn

### 💁‍♂️ PR 개요

- 페이지 라우팅 작업
- header 및 footer 레이아웃 구성
- husky 추가

<br/>

### 📷 스크린 샷 (선택)

<img width="167" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_28_FE/assets/108279922/9fbf36c4-96d8-46b9-9dfe-8763ef0a4b0b">

<br/>

### 🗣 리뷰어한테 할 말 (선택)

- 네이밍 마음에 안 들면 피드백 주세요!
- router.jsx에 path도 보시고 피드백 부탁드립니다 :)
- husky 작동되는 거 확인했습니다.

2024-03-16 02:09 UTC, a-honey requested changes
라우팅 좋네용

근데 저희 이제 마크업 스타일링 시작해야할거같아서 디자인까지 적용해주시면 좋을거같아요!
일단 더 빨리 나올거같아서 chakra-ui 같이하자고 한거였는데 혹시 css나 sass가 더 편하고 빠르실거같으면 Header.module.css 나 Header.module.scss 파일에서 작업해주시면될거같아요🌸🌸

2024-03-16 12:38 UTC, Sohyunnnn commented
<img width="960" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_28_FE/assets/108279922/88d195b6-8987-4147-8ae9-2323148c6efb">

이 정도인데 더 스타일이 들어가야 할까요?

2024-03-16 16:34 UTC, a-honey commented
> <img alt="image" width="960" src="https://private-user-images.githubusercontent.com/108279922/313404700-88d195b6-8987-4147-8ae9-2323148c6efb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDcwNDYsIm5iZiI6MTcxMDYwNjc0NiwicGF0aCI6Ii8xMDgyNzk5MjIvMzEzNDA0NzAwLTg4ZDE5NWI2LTg5ODctNDE0Ny04YWU5LTIzMjMxNDhjNmVmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxNjMyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDg0NDFjZWE3MGM1YmI5NmQ5ZTUxNTYxYTVhMzcyOTY1ZGUyMDYyNGE4ZDE4NGI2MmRiYmM4YTlkZWY2OTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cdfWqSAMCUVTXyQ7zIeBkn8mvOaGCiM07ufm7YtpR4A">
> 이 정도인데 더 스타일이 들어가야 할까요?

![image](https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_28_FE/assets/75254185/8a904043-3af8-4711-89a4-6281147ce100)

피그마 그대로 마크업해주시면될거같아요!

2024-03-17 13:40 UTC, Sohyunnnn commented
<img width="959" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_28_FE/assets/108279922/ab5c5647-4f68-41d9-94d6-139c1d512203">

이렇게 진행했습니다. 

로고 -> 추후 로고 나오면 변경 예정
스타트업 밸리 -> 이 부분도 글꼴 추가 후 변경하면 좋을 것 같아요!
마이페이지/ 로그인 -> 이 부분도 연동하면서 수정 예정

2024-03-17 15:18 UTC, a-honey approved these changes
넵 수고하셨습니당

2024-03-17 16:15 UTC, merged